name: ci

on:
  push:
    branches:
      - "*"


jobs:
  unit-tests:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      POSTGRES_TEST_DB: ${{ secrets.POSTGRES_TEST_DB }}
      TEST_POSTGRES_PORT: ${{ secrets.TEST_POSTGRES_PORT }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      TOKEN_EXPIRES: ${{ secrets.TOKEN_EXPIRES }}
      ALGORITHM: ${{secrets.ALGORITHM}}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt

      - name: Run unit tests
        run: pytest tests/unit_tests -v
